name: ScheduledRssRawler

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.5'

    - name: Install dependencies
      run: go mod tidy
      working-directory: ./api/GrabLatestRSS

    - name: Build
      run: go build -o main
      working-directory: ./api/GrabLatestRSS

    - name: Run Go program
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: 
      working-directory: ./api/GrabLatestRSS
