name: Trigger Sync Obsidian

on:
  repository_dispatch:
    types: [sync_from_obsidian]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Sync_Obsidian workflow
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'wangyunzi',
            repo: 'wangyunzi.github.io',
            workflow_id: 'Sync_Obsidian.yml',
            ref: 'master' // 指定触发的分支
          });
