name: Sync_Obsidian

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch to deploy'
        required: true
        default: 'master'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Obsidian repository
      uses: actions/checkout@v3
      with:
        repository: wangyunzi/myob
        path: myob
        token: ${{ secrets.OBSIDIAN_REPO_TOKEN }}

    - name: Checkout blog repository
      uses: actions/checkout@v3
      with:
        repository: wangyunzi/wangyunzi.github.io
        path: wangyunzi.github.io
        token: ${{ secrets.BLOG_REPO_TOKEN }}

    - name: List directories for debugging
      run: |
        echo "Listing myob"
        ls -R myob
        echo "Listing wangyunzi.github.io"
        ls -R wangyunzi.github.io

    - name: Convert date format
      run: |
        # Convert date format for _posts files
        for file in myob/日记本/_posts/*.md; do
          sed -i -r 's/^date: (.*)/date: \1 +0800/' "$file"
        done
        
        # Convert date format for _pages files
        for file in myob/日记本/_pages/*.md; do
          sed -i -r 's/^date: (.*)/date: \1 +0800/' "$file"
        done
        
        # Convert date format for _album files
        for file in myob/日记本/_album/*.md; do
          sed -i -r 's/^date: (.*)/date: \1 +0800/' "$file"
        done

        # Convert ISO 8601 date format to Jekyll compatible format
        for file in myob/日记本/_posts/*.md myob/日记本/_pages/*.md myob/日记本/_album/*.md; do
          sed -i -r 's/date: ([0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2})/date: \1 +0800/' "$file"
        done

    - name: Sync _pages folder
      run: |
        rsync -av --delete myob/日记本/_pages/ wangyunzi.github.io/_pages/
        cd wangyunzi.github.io
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add _pages
        git commit -m "Sync _pages from Obsidian repository" || echo "No changes in _pages"
        cd -

    - name: Sync _album folder
      run: |
        rsync -av --delete myob/日记本/_album/ wangyunzi.github.io/_album/
        cd wangyunzi.github.io
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add _album
        git commit -m "Sync _album from Obsidian repository" || echo "No changes in _album"
        cd -

    - name: Sync _posts folder
      run: |
        rsync -av --delete myob/日记本/_posts/ wangyunzi.github.io/_posts/
        cd wangyunzi.github.io
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add _posts
        git commit -m "Sync _posts from Obsidian repository" || echo "No changes in _posts"
        cd -

    - name: Push changes
      run: |
        cd wangyunzi.github.io
        git push
