name: Sync_Trigger

on:
  push:
    branches:
      - master

jobs:
  trigger_sync:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Sync_Obsidian Workflow
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.Trigger_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'wangyunzi',
            repo: 'wangyunzi.github.io',
            workflow_id: 'Sync_Obsidian.yml',
            ref: 'master' // 指定触发的分支
          });
