name: Sync_Obsidian

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch to deploy'
        required: true
        default: 'master'

jobs:
  sync:
    runs-on: ubuntu-latest
    concurrency:
      group: 'sync-obsidian'  # 确保只有一个工作流在运行
      cancel-in-progress: true  # 如果有新的请求，则取消当前请求

    steps:
    - name: Checkout Obsidian repository
      uses: actions/checkout@v3
      with:
        repository: wangyunzi/myob
        path: myob
        token: ${{ secrets.OBSIDIAN_REPO_TOKEN }}

    - name: Checkout blog repository
      uses: actions/checkout@v3
      with:
        repository: wangyunzi/wangyunzi.github.io
        path: wangyunzi.github.io
        token: ${{ secrets.BLOG_REPO_TOKEN }}

    - name: Sync folders
      run: |
        sync_folder() {
          local folder=$1
          rsync -av --delete myob/日记本/blog/$folder/ wangyunzi.github.io/$folder/
          cd wangyunzi.github.io || exit
          find $folder -name "*.md" -exec sed -i -E '
            s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2})T([0-9]{2}:[0-9]{2}:[0-9]{2})([+-][0-9]{2}:[0-9]{2}|)/date: \1 \2 +0800/
            s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2})T([0-9]{2}:[0-9]{2}:[0-9]{2})[+-][0-9]{2}:[0-9]{2}/date: \1 \2 +0800/
            s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2}) ([0-9]{2}:[0-9]{2}:[0-9]{2})/date: \1 \2 +0800/
          ' {} \;
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add $folder
          git commit -m "Sync $folder from Obsidian repository" || echo "No changes in $folder"
          cd - || exit
        }

        for folder in _pages _album _posts; do
          sync_folder $folder
        done

    - name: Push changes
      run: |
        cd wangyunzi.github.io || exit
        git push || echo "Failed to push changes. Please check the repository."